# Name GitHub workflow
name: Run Tests

# Define GitHub workflow trigger and run frequency 
on:
  push: # run frequency
    branches:
      - main

# Declare jobs and steps
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps: 
    # checkout repo
    - name: checkout repository 
      uses: actions/checkout@v3
    # install Python
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    # install dependencies 
    - name: Install dependencies 
      run: poetry install
    # run Pytest cases 
    - name: Run tests 
      run: poetry run pytest
